In [1]:
import numpy as np

In [2]:
int_ones=np.ones((2,2),dtype=np.int8)

In [3]:
int_ones

array([[1, 1],
       [1, 1]], dtype=int8)

In [4]:
uint_ones=np.ones((2,2),dtype=np.uint8)

In [5]:
uint_ones

array([[1, 1],
       [1, 1]], dtype=uint8)

In [6]:
string_arr=np.array(["Sam","Bill","Gary"])

In [7]:
string_arr

array(['Sam', 'Bill', 'Gary'],
      dtype='<U4')

In [8]:
vec1=np.array([1,-1,0],dtype=np.float16)

In [9]:
vec3=np.array([999],dtype=np.float64)

In [10]:
vec3

array([ 999.])

In [11]:
vec3[0]**vec3[0]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in double_scalars
  """Entry point for launching an IPython kernel.


inf

In [12]:
vec4=np.ones(5)

In [13]:
vec4

array([ 1.,  1.,  1.,  1.,  1.])

In [14]:
vec4[0]=np.nan

In [15]:
np.sum(vec4)

nan

In [16]:
np.nansum(vec4)

4.0

In [17]:
vec5=np.ones((5))

In [18]:
vec5.dtype

dtype('float64')

In [19]:
vec5.dtype=np.int8

In [20]:
print(vec5)

[  0   0   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0
   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0   0   0
   0   0 -16  63]


In [21]:
vec6=np.ones(5)

In [22]:
vec6

array([ 1.,  1.,  1.,  1.,  1.])